AntSwordProject/antSword

source/core/php/index.jsx
source/core/php/template/database/mysql.jsx

移除 DEPRECATED `set_magic_quotes_runtime`
升级 DEPRECATED mysql_*  到 mysqli_*
PHP 7 已经移除了那些函数

PHP 7 Support

---

source/core/php/template/database/informix.jsx
source/core/php/template/database/mssql.jsx
source/core/php/template/database/mysql.jsx
source/core/php/template/database/oracle.jsx
source/modules/database/php/index.jsx

增加base64编码，同时前端也html编码一次避免xss
只修改了php shell 类型的，实际测试php + mysql 通过

fix: 执行sql 语句时，如果数据本身包含换行符和html标签的情况

---

modules/request.js

优化数据截取处理算法

---

package.json

Add github-update-sources.

---

.gitignore
source/core/aspx/encoder/base64.jsx
source/core/aspx/index.jsx
source/core/aspx/template/base.jsx
source/core/aspx/template/filemanager.jsx

* 修补 aspx 连接和文件管理的 Bug
* 新添加了 aspx base64 编码器

fix(aspx): connect and filemanage bug

---

source/core/aspx/index.jsx
source/core/aspx/template/command.jsx
source/core/aspx/template/database/access.jsx
source/core/aspx/template/database/default.jsx
source/core/aspx/template/database/oracle.jsx
source/core/aspx/template/database/sqlserver.jsx
source/core/aspx/template/filemanager.jsx

fix(aspx): code auto encode

---

package.json

Add github update links

---

source/core/aspx/encoder/hex.jsx
source/core/aspx/index.jsx

new(aspx):add aspx hex encoder

---

source/core/php/index.jsx
source/core/php/template/database/mysql.jsx
source/core/php/template/database/mysqli.jsx
source/modules/database/php/index.jsx

将 PHP 中 mysql 与 mysqli 支持分离
* mysql 针对于  PHP5(没开启 Mysqli 情况下)
* mysqli 针对于 PHP5, PHP7
之前在 #12  中将 mysql 与 mysqli 合并了

php  mysql and mysqli

---

modules/database.js
shells/php_custom_script_for_mysql.php
source/core/asp/index.js
source/core/custom/template/database/sqlserver.js
source/core/php/template/database/mysql.js
source/core/php/template/database/mysqli.js
source/language/en.js
source/language/zh.js
source/modules/database/asp/index.js
source/modules/database/custom/index.js
source/modules/database/index.js
source/modules/database/php/index.js

* 新增编辑数据库配置
* 新增部分脚本执行 DML SQL 语句状态显示, 支持列表如下：
* PHP - Mysql
* PHP - Mysqli
* CUSTOM - PHP - Mysql
提到此功能的有: #36 #48

Edit db conf and php-mysql dml status

---

modules/cache.js
modules/database.js
modules/menubar.js
source/language/en.js
source/language/zh.js
source/modules/shellmanager/list/contextmenu.js
source/modules/shellmanager/list/form.js

在新的配置窗口中，添加了自定义HTTP头/主体内容 #57 功能，并且增加了其他设置选项，比如忽略HTTPS证书 #39 ，设置终端缓存&&自定义CMD执行目录（开发中） #58 
以及一些其他的优化改动。
> 当然，目前只是增加了数据库的配置而已，具体的功能实现代码并没有完成，不过有此基础之后一切都会很顺利哒！
- - -
> "都好，就好。"

v2.0-beta Advanced configure

---

modules/request.js
node_modules/superagent/lib/node/index.js
source/core/base.js

v2.0-beta::Ignore HTTPS Certificate

---

source/core/base.js
source/modules/shellmanager/list/form.js

增加随机编码器功能 #54 
> 从现有的编码器列表（包含default）中随机挑选一个编码器进行编码处理    
> **此功能针对多量编码器的时候才能发挥最大作用！**

v2.0-beta::random encoder features

---

modules/request.js
source/core/base.js

增加了自定义请求`HEADERS` && `BODYS`的功能
#57 #5

v2.0-beta::custom request headers && body

---

source/modules/shellmanager/list/form.js

Repair random selection Encoder

---

modules/request.js
source/core/base.js
source/modules/shellmanager/list/form.js

v2.0-beta::request timeout setting

---

source/language/en.js
source/language/zh.js
source/modules/shellmanager/list/form.js
source/modules/terminal/index.js

v2.0-beta::terminal nocache

---

modules/database.js
source/language/en.js
source/language/zh.js
source/modules/shellmanager/list/contextmenu.js
source/modules/viewsite/README.md
source/modules/viewsite/cookiemgr.js
source/modules/viewsite/index.js

v2.0-beta::Login authentication

---

source/language/en.js
source/language/zh.js
source/modules/shellmanager/list/form.js
source/modules/terminal/index.js

v2.0-beta::terminal custom execPath

---

source/modules/terminal/index.js

**增加虚拟终端模块的命令补全功能**
> 注意这里的补全命令为一些常用的命令，而并不等于目标站点上支持的命令

v2.0-beta::command complete

---

README.md
en/README.md
en/getting_started/aproxy_settings.md
en/getting_started/first_shell.md
en/getting_started/get_antsword.md
en/plugin_store/README.md
en/plugin_store/plugin_store_settings.md
en/plugins/load_plugin.md
en/shell_manager/category.md
en/shell_manager/main_page.md
en/shell_manager/shell_config.md

1. fix spell errors in `en/`(major changes)
2. add English introduction in README.md
3. delete some Chinese which should be deleted in `en/`

Fix spell errors

---

modules/menubar.js
source/app.entry.js
source/core/asp/index.js
source/core/aspx/index.js
source/core/custom/index.js
source/core/php/index.js
source/language/en.js
source/language/zh.js
source/load.entry.js
source/modules/settings/encoders.js
source/modules/settings/index.js

Add Encoder Manager module

---

modules/request.js

support 404 status

---

source/app.entry.js
source/language/en.js
source/language/zh.js
source/language/zh_hk.js
source/language/zh_tw.js
source/modules/shellmanager/index.js
source/modules/shellmanager/toolbar.js

插件package.jsoon新增字段 global 用于判断是否需要shell信息
global:true 不需要选择 shell
global:false  至少选择一个 shell

(Enhance: Source::ShellManger::Toolbar) 新增插件工具栏

---

modules/request.js
source/core/base.js
source/language/en.js
source/language/zh.js
source/language/zh_hk.js
source/language/zh_tw.js
source/modules/shellmanager/list/form.js

可用于常见waf的bypass，如安全狗，云锁，以及阿里云。
详情：https://yzddmr6.tk/posts/antsword-diy-1/

新功能增加：增加垃圾数据填充功能

---

source/core/asp/index.js
source/core/aspx/index.js
source/core/aspx/template/command.js
source/core/aspx/template/filemanager.js

1. 修复asp aspx无法使用的bug
2. 给aspx其他参数前加上随机前缀

Bug Fix & 给aspx增加随机前缀
